### ISSUE TITLE
Bagfile has no data

### ISSUE THREAD

**Issue by JeroenDM** [Bart123456/lasrobot_ws#11]
It looks like there's no data in the file trajectory.bag.

Output of `rosbag info trajectory.bag`

> path:        trajectory.bag
> version:     2.0
> duration:    0.0s
> start:       Mar 29 2017 13:18:10.35 (1490786290.35)
> end:         Mar 29 2017 13:18:10.35 (1490786290.35)
> size:        5.1 MB
> messages:    2
> compression: none [1/1 chunks]
> types:       moveit_msgs/PlanningScene       [89aac6d20db967ba716cba5a86b1b9d5]
>              trajectory_msgs/JointTrajectory [65b4f94a94d1ed67169da35a02f33d3f]
> topics:      planningscene   1 msg     : moveit_msgs/PlanningScene      
>              trajectory      1 msg     : trajectory_msgs/JointTrajectory

**Comment by Bart123456** [comment]
The bag file is filled with a PlanningScene message, containing information about the planning scene for the scenario. It also contains a JointTrajectory message, this contains all the generated joint poses for the robot and can be executed directly in moveit.

The bag file is certainly not empty.
