### ISSUE TITLE
Save data in csv format

### ISSUE THREAD

**Issue by JeroenDM** [Bart123456/lasrobot_ws#12]
I'm thinking about directly writing the data to a csv file after execution. Analyzing the data will probably be done outside ros, where bagfiles are quite useless. Or, we can convert the bagfile with a script like [this](http://www.speal.ca/bag2csv.py).

**Comment by Bart123456** [comment]
Although it certainly wouldn't hurt, I have actually used the JointTrajectory information directly from a bag file today. I used it to generate a graph using Matplotlib in python. Quite easy actually. I will probably upload the necessary files soon.
