### ISSUE TITLE
Duration of path generation

### ISSUE THREAD

**Issue by Bart123456** [Bart123456/lasrobot_ws#7]
Currently the pathgeneration takes pretty long. For a couple of cartesian points (~10) with multiple angular tolerances and a pretty big discretization step size it takes minutes to compute a trajectory.
The bottleneck seems to be the solving of the inverse kinematics, and perhaps the collision checking.

**Comment by JeroenDM** [comment]
I added the kr120 robot of the [kuka experimental](https://github.com/ros-industrial/kuka_experimental) package. This robot has convex meshes for collision checking. I added an ikfast package for this robot.
The Descartes path planning runs a lot faster now (seconds instead of minutes).

**Comment by Bart123456** [comment]
This issue seems to be solved.
See #9
